<?php
/**
 * @file
 * lumc_taxonomy_relationship_type.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function lumc_taxonomy_relationship_type_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_inverse_relation_text'.
  $field_bases['field_inverse_relation_text'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_inverse_relation_text',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_relation_text'.
  $field_bases['field_relation_text'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_relation_text',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
