<?php
/**
 * @file
 * lumc_facet_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function lumc_facet_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-15fFpDbtYDQvBH2tbiDWsrNJ0VjWmUH5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '15fFpDbtYDQvBH2tbiDWsrNJ0VjWmUH5',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'learning-paths',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 1,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'System',
    'visibility' => 1,
  );

  $export['facetapi-1dqXMBK04PQFIq1KcSRB9Kc6chggdd78'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1dqXMBK04PQFIq1KcSRB9Kc6chggdd78',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'introductions
embryology
microscopy
radiology
anatomy_in_practice
documents
images
videos
interactive
gallery
gallery/*',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 5,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'System',
    'visibility' => 1,
  );

  $export['facetapi-5sW19NU1z1YLbWLRMrIMnwiOrUNqWBcO'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '5sW19NU1z1YLbWLRMrIMnwiOrUNqWBcO',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'documents
images
videos
interactive
gallery
gallery/*',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 6,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Topics',
    'visibility' => 1,
  );

  $export['facetapi-6tfO0nrT15w07zKQTkHWs0EDW3Q51Gfi'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '6tfO0nrT15w07zKQTkHWs0EDW3Q51Gfi',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'learning-paths',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 5,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Institution',
    'visibility' => 1,
  );

  $export['facetapi-CnOSAZIHseE2lD10QB4gL45Jw1WNSDfA'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'CnOSAZIHseE2lD10QB4gL45Jw1WNSDfA',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'learning-paths',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => -2,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Anatomical structure',
    'visibility' => 1,
  );

  $export['facetapi-FS5Vl0x4DESD1hwJ0kmjwd112V09YJpN'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'FS5Vl0x4DESD1hwJ0kmjwd112V09YJpN',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'anatomy_in_practice',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 8,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Anatomy in practice type',
    'visibility' => 1,
  );

  $export['facetapi-GaDrMmh0X882d1MxKeWJekGuhSGowpyh'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'GaDrMmh0X882d1MxKeWJekGuhSGowpyh',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'introductions
embryology
microscopy
dissection
radiology
anatomy_in_practice
documents
images
videos
interactive',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 0,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Anatomical structure',
    'visibility' => 1,
  );

  $export['facetapi-GgUxkN6i166ATsjy12guhTmlAkQFNmZN'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'GgUxkN6i166ATsjy12guhTmlAkQFNmZN',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'radiology
images',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 10,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Image Technique',
    'visibility' => 1,
  );

  $export['facetapi-LpN6hIdijGC212CVt6lGrY6nC0HJd8RI'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'LpN6hIdijGC212CVt6lGrY6nC0HJd8RI',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'learning-paths',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 6,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'License',
    'visibility' => 1,
  );

  $export['facetapi-M7qowoIv7StIfiZKXHhqPfgKXQ1nHMT1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'M7qowoIv7StIfiZKXHhqPfgKXQ1nHMT1',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'introductions
embryology
microscopy
dissection
radiology
anatomy_in_practice
gallery
gallery/*',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 2,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Format',
    'visibility' => 1,
  );

  $export['facetapi-N7UdtZvGwWkUeRbJdxURtT7uj8uQrtYB'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'N7UdtZvGwWkUeRbJdxURtT7uj8uQrtYB',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'learning-paths',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 4,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Level',
    'visibility' => 1,
  );

  $export['facetapi-P9YUTVH4SOsnnBNVZhBl1sKfUSTVmmsJ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'P9YUTVH4SOsnnBNVZhBl1sKfUSTVmmsJ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'embryology
dissection
radiology
anatomy_in_practice
images',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 12,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Image view direction',
    'visibility' => 1,
  );

  $export['facetapi-T1qaOo1JX0Q53bIOwBbXXciobFxx6bXZ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'T1qaOo1JX0Q53bIOwBbXXciobFxx6bXZ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'introductions
embryology
microscopy
dissection
radiology
anatomy_in_practice
documents
images
videos
interactive
gallery/*',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 1,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Relations',
    'visibility' => 1,
  );

  $export['facetapi-U9qAiPSTMASHukvvGnORTf19IIwcfIJJ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'U9qAiPSTMASHukvvGnORTf19IIwcfIJJ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'learning-paths',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => -1,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Relations',
    'visibility' => 1,
  );

  $export['facetapi-VKcBlQ1Bl1SRGvZ4a6bywgFPxdXslN9G'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'VKcBlQ1Bl1SRGvZ4a6bywgFPxdXslN9G',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'microscopy',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 3,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Image type',
    'visibility' => 1,
  );

  $export['facetapi-XAuLHpWZGnd6geU8Ld9Ditu4PN9EfjkX'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'XAuLHpWZGnd6geU8Ld9Ditu4PN9EfjkX',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'introductions
embryology
microscopy
dissection
radiology
anatomy_in_practice
documents
images
videos
interactive
gallery
gallery/*',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 16,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'License',
    'visibility' => 1,
  );

  $export['facetapi-Zq5Nw4fhiBBWCZY1fTAcOQU3DLHtTzbL'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Zq5Nw4fhiBBWCZY1fTAcOQU3DLHtTzbL',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'learning-paths',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 0,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Region',
    'visibility' => 1,
  );

  $export['facetapi-f0Q7SnD0MApsGtWOwGfV9walPudDrlxa'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'f0Q7SnD0MApsGtWOwGfV9walPudDrlxa',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'learning-paths',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 2,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Topics',
    'visibility' => 1,
  );

  $export['facetapi-gxgHSI0cG7hGv0S4QmDfyLRkPKnsY9DB'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'gxgHSI0cG7hGv0S4QmDfyLRkPKnsY9DB',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'introductions
embryology
microscopy
dissection
radiology
anatomy_in_practice
documents
images
videos
interactive
gallery
gallery/*',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 13,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Language',
    'visibility' => 1,
  );

  $export['facetapi-hw0l10w0rIuFnxB0m0xPjVsRVJpjdE4p'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'hw0l10w0rIuFnxB0m0xPjVsRVJpjdE4p',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'radiology
anatomy_in_practice',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 7,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Clinical Discipline',
    'visibility' => 1,
  );

  $export['facetapi-mZACWXbRkyLaMVNBADEORZGuTHzQmLK1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'mZACWXbRkyLaMVNBADEORZGuTHzQmLK1',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'learning-paths',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 3,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Language',
    'visibility' => 1,
  );

  $export['facetapi-nUh22EoLxA8HRJHy05uHSagTzbokxkEr'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'nUh22EoLxA8HRJHy05uHSagTzbokxkEr',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'images',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 9,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Image collection',
    'visibility' => 1,
  );

  $export['facetapi-qBxvUOjV5svUFwXOBBx3tBqmzb1fy9kk'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'qBxvUOjV5svUFwXOBBx3tBqmzb1fy9kk',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'introductions
embryology
microscopy
dissection
radiology
anatomy_in_practice
documents
images
videos
interactive
gallery
gallery/*',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 14,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Level',
    'visibility' => 1,
  );

  $export['facetapi-qoOS781XxFdSVspEO0hh94RNcFKdgVJd'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'qoOS781XxFdSVspEO0hh94RNcFKdgVJd',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'microscopy',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 11,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Technique/staining',
    'visibility' => 1,
  );

  $export['facetapi-tjA1x0HBQRCxOTbFAsS4KfTXTf4okOq5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'tjA1x0HBQRCxOTbFAsS4KfTXTf4okOq5',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'introductions
embryology
microscopy
dissection
radiology
anatomy_in_practice
documents
images
videos
interactive
gallery
gallery/*',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 15,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Institution',
    'visibility' => 1,
  );

  $export['facetapi-zp09FwWM7QJ33Cqerb4XMmgbzIHXYE1D'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'zp09FwWM7QJ33Cqerb4XMmgbzIHXYE1D',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'introductions
embryology
dissection
radiology
anatomy_in_practice
documents
images
videos
interactive
gallery
gallery/*',
    'roles' => array(),
    'themes' => array(
      'lumc' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'lumc',
        'weight' => 4,
      ),
      'platon' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'platon',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Region',
    'visibility' => 1,
  );

  return $export;
}
